docs update, QOL improvements

diff --git a/general/overlay/etc/init.d/S90masinaclient b/general/overlay/etc/init.d/S90masinaclient
--- a/general/overlay/etc/init.d/S90masinaclient
+++ b/general/overlay/etc/init.d/S90masinaclient
@@ -1,46 +1,52 @@
 #!/bin/sh
 
-DAEMON="/usr/bin/masinaclient"
-PIDFILE="/var/run/client.pid"
-DAEMON_ARGS=""
+DAEMON="masinaclient"
+PIDFILE="/var/run/$DAEMON.pid"
+DAEMON_ARGS="-s"
+
+if [ -e /root/masina ]; then
+	. /root/masina
+fi
 
 start() {
-    ulimit -c unlimited
-    echo "/tmp/core.client" > /proc/sys/kernel/core_pattern
-
-    echo -n "Starting Masina client..."
-    start-stop-daemon -b -m -S -q -p "$PIDFILE" -x "$DAEMON" -- $DAEMON_ARGS
-    if [ $? -eq 0 ]; then
-        echo "OK"
-    else
-        echo "FAIL"
-    fi
+	if [ "$enabled" = "true" ]; then
+		echo -n "Starting Masina client..."
+		start-stop-daemon -b -m -S -q -p "$PIDFILE" -x "$DAEMON" -- $DAEMON_ARGS
+		if [ $? -eq 0 ]; then
+			echo "OK"
+		else
+			echo "FAIL"
+		fi
+	else
+		echo "Masinaclient is disabled in /root/masinaclient"
+		exit 1
+	fi
 }
 
 stop() {
-    echo -n "Stopping Masina client: "
-    start-stop-daemon -K -q -p "$PIDFILE"
-    if [ $? -eq 0 ]; then
-        rm -f "$PIDFILE"
-        echo "OK"
-    else
-        echo "FAIL"
-    fi
+	echo -n "Stopping Masina client: "
+	start-stop-daemon -K -q -p "$PIDFILE"
+	if [ $? -eq 0 ]; then
+		rm -f "$PIDFILE"
+		echo "OK"
+	else
+		echo "FAIL"
+	fi
 }
 
 case "$1" in
-    start|stop)
-        $1
-        ;;
+start | stop)
+	$1
+	;;
 
-    restart|reload)
-        stop
-        sleep 3
-        start
-        ;;
+restart | reload)
+	stop
+	sleep 3
+	start
+	;;
 
-    *)
-        echo "Usage: $0 {start|stop|restart|reload}"
-        exit 1
-        ;;
+*)
+	echo "Usage: $0 {start|stop|restart|reload}"
+	exit 1
+	;;
 esac
